openapi: 3.0.0
info:
  title: Trail API
  version: 1.0.0
paths:
  /trails:
    get:
      summary: Get all trails
      responses:
        '200':
          description: A list of trails
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Trail'
    post:
      summary: Create a new trail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trail'
      responses:
        '201':
          description: The created trail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trail'
  /trails/{id}:
    get:
      summary: Get a trail by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The trail with the specified ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trail'
    put:
      summary: Update a trail by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trail'
      responses:
        '200':
          description: The updated trail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trail'
    delete:
      summary: Delete a trail by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No content
components:
  schemas:
    Trail:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        city:
          type: string
        state:
          type: string
        rating:
          type: number
          format: double
        difficulty:
          type: string
        length:
          type: number
          format: double
        time:
          type: number
          format: double
        pace:
          type: number
          format: double
        images:
          type: array
          items:
            type: string
            format: uri
        username:
          type: string
        date:
          type: string
          format: date-time
        description:
          type: string