name: EAS Build
on:
  workflow_dispatch:
  pull_request:
    branches: [ "main", "develop" ]
jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        working-directory: ./mobile
        uses: actions/setup-node@v4
        with:
          node-version: 22.10.0
          cache: npm

      - name: Install dependencies
        working-directory: ./mobile
        run: npm ci

      - name: Setup Expo and EAS
        working-directory: ./mobile
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build on EAS
        working-directory: ./mobile
        run: eas build --platform all --non-interactive --no-wait
